(define (domain clutter)
 (:requirements :strips :equality)
 (:predicates (on-surface ?x -objs ?surf -surface :discrete)
  (arm-empty ?m -manipulator :discrete)
  (holding ?m -manipulator ?x -objs :kinematic ((link ?m ?x) (unlink ?m ?x)))
  (on ?x -objs ?y -objs)
  (at ?m -manipulator ?x -objs)
  (above ?m -manipulator ?surf -surface)
  (manhattanat ?m -manipulator ?x -objs)
  (donthit ?l -link ?o -objs)
  (donthits ?l -link ?s -surface))

 (:action pickup
  :parameters (?ob -objs ?surf -surface ?m -manipulator)
  :precondition (and
    (on-surface ?ob ?surf)
    (arm-empty ?m)
    (manhattanat ?m ?ob)
    (donthits l_upper_arm_link ?surf)
    (donthits l_forearm_link ?surf)
    (donthits r_upper_arm_link ?surf)
    (donthits r_forearm_link ?surf))
  :effect (and (holding ?m ?ob) (not (on-surface ?ob ?surf)) 
    (not (arm-empty ?m))))

 (:action putdown
  :parameters (?ob -objs ?surf -surface ?m -manipulator)
  :precondition (and (above ?m ?surf)
    (holding ?m ?ob)
    (donthits l_upper_arm_link ?surf)
    (donthits l_forearm_link ?surf)
    (donthits r_upper_arm_link ?surf)
    (donthits r_forearm_link ?surf))
  :effect (and (arm-empty ?m) (on-surface ?ob ?surf) (not (holding ?m ?ob)))))
